/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yukasir;

import yukasir.model.Product;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import yukasir.controller.ProductController;

/**
 *
 * @author Paideia
 */
public class App extends javax.swing.JFrame {

    List<Product> products;
    ProductController controller = new ProductController();
    
    private Map<String, Transaction> basketMap = new HashMap<>();
    private int total = 0;
    
    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        basketMap.clear();
        
        try {
            products = controller.getAll();
            if(products.size()>0){
                initLayout();
            }
        } catch (SQLException ex) {
            Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void initLayout(){
        setExtendedState(JFrame.MAXIMIZED_BOTH); 

        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI(10));
        jScrollPane1.getHorizontalScrollBar().setUI(new CustomScrollBarUI(10));
        
        
        scrollSide.getVerticalScrollBar().setUI(new CustomScrollBarUI(0));
        scrollSide.getHorizontalScrollBar().setUI(new CustomScrollBarUI(0));
                
        JPanel container = new JPanel();
        container.setLayout(new BoxLayout(container, BoxLayout.X_AXIS));
        content.add(container);

        for (int i = 0; i < products.size(); i++) {
            int index = i;
            Card card = new Card();
            card.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    var transaction = basketMap.get(Integer.toString(products.get(index).id));
                    
                    if(transaction == null){
                         Transaction trx = new Transaction(products.get(index));
                        basketMap.put(Integer.toString(products.get(index).id), trx);
                        updateBasket();
                    }else{
                        transaction.incrementQuantity();
                        updateBasket();
                    }       
                }

            });
            card.setProduct(products.get(index));
            container.add(card);

            if ((i + 1) % 4 == 0) {
                container = new JPanel();
                container.setLayout(new BoxLayout(container, BoxLayout.X_AXIS));
                content.add(container);
            }
        }
        
        int remaining = products.size() % 4;
        if (remaining != 0) {
            int emptyPanelsNeeded = 4 - remaining;
            for (int i = 0; i < emptyPanelsNeeded; i++) {
                Card card = new Card();
                card.setEmpty();
                container.add(card);
            }
        }
    }
    
    public void updateBasket() {
        total = 0;
        basket.removeAll();
        basketMap.forEach((id,transaction)->{
            total+=transaction.pricePerUnit*transaction.quantity;
            Checkout checkout = new Checkout();
            checkout.setCheckout(transaction.name, transaction.pricePerUnit, transaction.quantity);
            checkout.onRemove(data->{
                if(transaction.quantity > 1){
                    transaction.decrementQuantity();
                }else{
                    basketMap.remove(Integer.toString(transaction.id));
                }
                updateBasket();
            });
            basket.add(checkout);
        });
        NumberFormat numberFormat = NumberFormat.getInstance(Locale.GERMANY);
        totalBayar.setText("Bayar    Rp"+numberFormat.format(total));
        basket.revalidate();
        basket.repaint(); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scrollSide = new javax.swing.JScrollPane();
        basket = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        totalBayar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(500, 6));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new javax.swing.BoxLayout(content, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(content);

        getContentPane().add(jScrollPane1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 32767));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 541));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(183, 209, 206));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel3.setMinimumSize(new java.awt.Dimension(97, 60));
        jPanel3.setPreferredSize(new java.awt.Dimension(359, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Transaksi");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(105, 105, 105)
                .addComponent(jLabel2)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13))
        );

        jPanel1.add(jPanel3);

        scrollSide.setBorder(null);
        scrollSide.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollSide.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        basket.setBackground(new java.awt.Color(255, 255, 255));
        basket.setLayout(new javax.swing.BoxLayout(basket, javax.swing.BoxLayout.Y_AXIS));
        scrollSide.setViewportView(basket);

        jPanel1.add(scrollSide);

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel4.setPreferredSize(new java.awt.Dimension(359, 60));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 18));

        totalBayar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        totalBayar.setForeground(new java.awt.Color(255, 255, 255));
        totalBayar.setText("Bayar    Rp0");
        jPanel4.add(totalBayar);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        LocalStorage.removeData("auth");
                    
        Login login = new Login();
        login.setVisible(true);
                    
        setVisible(false);
        dispose();

    }//GEN-LAST:event_jLabel2MousePressed

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
        Payment payment = new Payment(total, basketMap);
        payment.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel4MousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new App().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basket;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scrollSide;
    private javax.swing.JLabel totalBayar;
    // End of variables declaration//GEN-END:variables
}
