/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package yukasir;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.function.Consumer;

/**
 *
 * @author Paideia
 */
public class Checkout extends javax.swing.JPanel {
    
    /**
     * Creates new form Checkout
     */
    public Checkout() {
        initComponents();
    }
    
    public void setCheckout(String name,int price,int quantity){
        productName.setText(name);
        NumberFormat numberFormat = NumberFormat.getInstance(Locale.GERMANY);
        detail.setText("x"+quantity+"   Rp"+numberFormat.format(price));
    }
    
    public void onRemove(Consumer<Checkout> onRemove){
        Checkout checkout = this;
        remove.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent e) {
                onRemove.accept(checkout);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        productName = new javax.swing.JLabel();
        detail = new javax.swing.JLabel();
        remove = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(32767, 32));
        setPreferredSize(new java.awt.Dimension(400, 32));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(344, 45));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {360};
        jPanel1Layout.columnWeights = new double[] {6.0};
        jPanel1.setLayout(jPanel1Layout);

        productName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        productName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        productName.setText("Kepiting Saus Padang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel1.add(productName, gridBagConstraints);

        detail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        detail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detail.setText("x5  Rp 50.000");
        detail.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 12;
        jPanel1.add(detail, gridBagConstraints);

        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remove.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 12;
        jPanel1.add(remove, gridBagConstraints);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel remove;
    // End of variables declaration//GEN-END:variables
}
